### ISSUE TITLE
Differing licenses

### ISSUE THREAD

**Issue by djmattyg007** [luckydonald/luckydonald-utils#1]
The LICENSE file contains the text of the GPL version 2, but setup.py lists the license as GPL version 3 or higher.

**Comment by luckydonald** [comment]
See https://github.com/luckydonald/pytg/issues/75

**Comment by luckydonald** [comment]
If you use it, and change it, it needs to be released open source. 
Also all this _I don't owe you anything if you destroy stuff with my code_
